[tool.poetry]
name = "meu-projeto"
version = "0.1.0"
description = ""
authors = ["kauanlopeskkk <kauanlopes2706@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
